# Generated by Django 5.0.3 on 2024-03-25 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostasQuestionarioInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta1', models.CharField(choices=[('S', 'Sim'), ('MM', 'Mais ou menos'), ('N', 'Não')], max_length=2)),
                ('pergunta2', models.CharField(choices=[('S', 'Sim'), ('MM', 'Mais ou menos'), ('N', 'Não')], max_length=2)),
                ('pergunta3', models.CharField(choices=[('S', 'Sim'), ('MM', 'Mais ou menos'), ('N', 'Não')], max_length=2)),
                ('pergunta4', models.CharField(choices=[('NA', 'Não organizo'), ('NAV', 'Não organizo, pois tenho acesso a valores financeiros muito baixos'), ('MS', 'Me organizo somente para os gastos mais altos'), ('RPM', 'Registro em planilhas todos os meus gastos mensais'), ('O', 'Outros')], max_length=3)),
                ('pergunta5', models.CharField(choices=[('S', 'Sim'), ('MM', 'Mais ou menos'), ('N', 'Não')], max_length=2)),
                ('pergunta6', models.CharField(choices=[('DGNI', 'Deixaria guardado e não investiria, pois desconheço qualquer tipo de investimento'), ('IB', 'Investiria em bens (casa, carro, apartamento, etc.)'), ('IA', 'Investiria em ações, pela possibilidade de altos ganhos, mesmo sabendo do risco elevado de perdas'), ('IRF', 'Investiria em renda fixa de risco médio, porém com retornos acima da inflação'), ('ITG', 'Investiria em títulos do governo, como títulos do Tesouro, mesmo com possíveis turbulências governamentais e/ou crise instalada no país'), ('IP', 'Investiria em poupança, mesmo rendendo a mesma taxa de inflação, pois priorizo a segurança em relação ao meu dinheiro')], max_length=4)),
                ('pergunta7', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
