# Generated by Django 5.0.3 on 2024-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbolsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostasquestionarioinicial',
            name='pergunta7',
            field=models.TextField(max_length=500),
        ),
    ]
